### ISSUE TITLE
替换GitHub的client_id和client_secret后, 登录时提示账号或密码错误

### ISSUE THREAD

**Issue by PiggyDance** [ddnosh/QuickHub-Java-MVVM#1]
已经按照README在private.properties中填写了自己的client_id和client_secret, 账号和密码也是正确的, 但登录时提示账号或密码错误, Http返回401错误.
请问是否还有其他需要自己替换的项但README中没有指明导致认证错误的呢?

**Comment by PiggyDance** [comment]
https://github.com/jianjunxiao/wanandroid
这个wanandroid客户端也不错, kotlin实现

**Comment by ddnosh** [comment]
@Narutow GitHub在2020/11/13已经移除了原有的Authorizations API endpoint接口，所以目前只支持使用Browser进行OAuth登录。新的代码已经提交，在分支：book_source_code_feature。
